language: node_js
node_js:
  - '10.16.3' # Lambda version as of 2019-11-21
before_script:
  - npm install -g zapier-platform-cli
script:
  - npm run lint
  - npm run build
  - npm run zapier-test
after_success:
  - >
    test $TRAVIS_BRANCH = "master" &&
    echo "{\"deployKey\": \"$ZAPIER_DEPLOY_KEY\"}" > ~/.zapierrc &&
    npm run push
notifications:
  email: false
